Basis-Theory/basis-theory-js

.github/workflows/pull-request.yml
.github/workflows/release.yml
library/.releaserc.json

Update secret name for Azure login on workflows.

chore: change azure login secret

---

LICENSE
README.md

- Add badges and update license

chore: update license

---

library/src/atomic/banks/BasisTheoryAtomicBanks.ts
library/src/atomic/cards/BasisTheoryAtomicCards.ts
library/src/common/utils.ts
library/src/reactors/BasisTheoryReactors.ts
library/src/service/types.ts
library/src/tokens/BasisTheoryTokens.ts
library/test/applications.test.ts
library/test/atomic_banks.test.ts
library/test/atomic_cards.test.ts
library/test/permissions.test.ts
library/test/setup/utils.ts
library/test/tenants.test.ts
library/test/tokens.test.ts

- Added missing concatenation w/ axios default transformers on clients/requests custom request/response transformers.
- Added `JSON.stringify()` to tests reply to accurately represent production scenarios.

ENG-1277 - Fix custom request/response transformers.

---

.github/ISSUE_TEMPLATE.md

[no ci] chore: ENG-1282 Update discord link

---

e2e/cypress/integration/elements.spec.ts
package.json
yarn.lock

- Bump cypress version to ^8.3.1
- Fix issue w/ elements cypress test

ENG-1301 - Bump cypress version

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
scripts/acceptance.sh
scripts/build.sh

Adds SKIP_INSTALL_FLAG and caches Cypress by version for workflow optimization
-
Faster feedback loops

ENG-1188 - Standardize workflow files and scripts

---

.github/CODEOWNERS
library/src/tenants/types.ts
library/test/tenants.test.ts

- Adds new property to TenantUsageReport.TokenReport for `monthly_active_tokens`

feat: add monthly_active_tokens to TenantUsageReport

---

library/src/tenants/types.ts
library/test/tenants.test.ts

- Remove enrichment fields from tenant usage report

feat: remove enrichment fields from tenant usage report

---

library/src/tenants/types.ts
library/test/tenants.test.ts

- Adds included monthly active tokens field to tenant usage report

feat: add included monthly active tokens field to tenant usage report

---

library/src/logs/types.ts

- Adds `actor_id` and `actor_type` properties to Log response model
- Removes `application_id` property which is replaced by `actor_id`

feat: add actor_id and actor_type to Log response model

---

library/src/atomic/banks/BasisTheoryAtomicBanks.ts
library/src/atomic/cards/BasisTheoryAtomicCards.ts
library/src/atomic/types.ts
library/src/common/utils.ts
library/src/tokens/types.ts
library/test/atomic-banks.test.ts
library/test/atomic-cards.test.ts

feat: use new react response schema and remove get reaction by id

---

e2e/cypress/integration/credit-card.spec.ts
examples/credit_card.html
library/src/BasisTheory.ts
library/src/atomic/banks/BasisTheoryAtomicBanks.ts
library/src/atomic/cards/BasisTheoryAtomicCards.ts
library/src/atomic/cards/types.ts
library/src/common/constants.ts
library/src/common/utils.ts
library/src/tokenize/BasisTheoryTokenize.ts
library/src/tokenize/index.ts
library/src/tokens/BasisTheoryTokens.ts
library/src/tokens/types.ts
library/src/types.ts
library/test/atomic-cards.test.ts
library/test/atomic.test.ts
library/test/clients.test.ts
library/test/tokenize.test.ts
library/test/tokens.test.ts

feat: add tokenize endpoint, remove billing details, removes children filters

---

.github/workflows/release.yml

Adds integration test dispatch when releasing

ENG-1851 - add integration tests workflow dispatch

---

library/src/tokenize/BasisTheoryTokenize.ts
library/src/tokenize/types.ts

ENG-1909 - fix: tokenize types

---

README.md
library/src/common/constants.ts
library/test/clients.test.ts

feat: convert to use BT-API-KEY for auth header

---

library/package.json
yarn.lock

- Bumps `basis-theory-elements-interfaces` to enable new password option for text element

ENG-1915 - feat: bump elements interfaces to add new password field to text element

---

library/package.json
library/src/BasisTheory.ts
library/src/elements/services/tokenize.ts
library/src/tokenize/BasisTheoryTokenize.ts
library/test/elements/create.test.ts
library/test/elements/tokenize.test.ts
library/test/init.test.ts
library/test/setup/utils.ts
library/test/tokenize.test.ts
library/test/utils.test.ts
yarn.lock

⚠️  Coordinate release with elements, hosted elements and docs  ⚠️ 
Turns `BasisTheory#tokenize` into a method the user may invoke directly

ENG-1917 - feat: turns `tokenize` into a SDK method

---

library/package.json
library/src/tokens/BasisTheoryTokens.ts
library/test/tokens.test.ts

feat: exposing token search

---

library/package.json
library/webpack.common.js
yarn.lock

- Adds polyfill for `os` module
- Bundle size increases around 1kb. 
Install this version of the package on a React project created w/ CRA

ENG-2217 - fix: add polyfill for os module for webpack users

---

.github/CODEOWNERS

chore(ENG-2473): update codeowners

---

library/package.json
library/src/atomic/banks/BasisTheoryAtomicBanks.ts
library/src/atomic/cards/BasisTheoryAtomicCards.ts
library/src/common/utils.ts
library/src/reactors/BasisTheoryReactors.ts
library/test/reactor-formulas.test.ts
library/test/reactors.test.ts
yarn.lock

- exposing new react endpoint
- this depends on elements interfaces pr https://github.com/Basis-Theory/basis-theory-elements-interfaces/pull/95

feat: exposing new react endpoint

---

scripts/setupinfra.sh

- Adds `--overwrite` flag to storage uploads since overwrite behavior is now disabled by default

fix: overwrite existing files in storage [ci skip]

---

library/package.json
library/src/common/utils.ts
library/src/tenants/BasisTheoryTenants.ts
library/test/tenants.test.ts
yarn.lock

- Adds new methods to manage Tenant Members
- `bt.tenants.listMembers`
- `bt.tenants.deleteMember`
- Adds new methods to manage Tenant Invitations
- `bt.tenants.createInvitation`
- `bt.tenants.resendInvitation`
- `bt.tenants.listInvitations`
- `bt.tenants.retrieveInvitation`
- `bt.tenants.deleteInvitation`

feat: add Tenant Invitations and Tenant Members operations

---

library/src/common/index.ts

Exports `BasisTheoryValidationError`

fix: export validation error

---

src/BasisTheory.ts
src/types/elements/elements.ts
src/types/elements/events.ts

Adds `cardBrand` specification to Card Element change event

feat: add cardBrand to card element change event

---

src/BasisTheory.ts
src/types/elements/elements.ts
src/types/elements/events.ts
src/types/elements/options.ts
src/types/elements/services/tokenize.ts
src/types/elements/services/tokens.ts

Adds `CardExpirationDateElement` types

feat: add CardExpirationDateElement types

---

src/BasisTheory.ts
src/elements/constants.ts
src/types/elements/elements.ts
src/types/elements/events.ts
src/types/elements/options.ts
src/types/elements/shared.ts

- Add types for new CardVerificationCodeElement

feat: add CardVerificationCodeElement types

---

src/BasisTheory.ts
src/types/elements/elements.ts
src/types/elements/events.ts
src/types/elements/options.ts

- Adds `CardNumberElement` types

feat: add CardNumberElement types

---

src/types/models/tokens.ts
test/tokenize.test.ts
test/tokens.test.ts

- Add search_indexes to post /tokens and /tokenize, and token responses

feat: adding search indexes to token creation and responses

---

src/types/models/tokens.ts
test/tokenize.test.ts
test/tokens.test.ts

- adds `fingerprint_expression` on Tokens

feat: adds fingerprint_expression prop on Token

---

src/types/models/proxies.ts
test/proxies.test.ts

- Adds Require Auth property to the Proxy entity

feat: add requireAuth property to proxy entity

---

.gitignore
.vscode/settings.json
src/types/models/proxies.ts
test/proxies.test.ts

- Adds Response Reactor to the Proxy entity

feat: add response reactor to proxy

---

src/types/models/tenants.ts
src/types/models/tokens.ts
test/tenants.test.ts
test/tokens.test.ts

- Adds settings to tenant and deduplicate token option to tokens

feat: add tenant settings and tokens deduplicate option

---

src/types/models/tokens.ts
test/tokenize.test.ts
test/tokens.test.ts

feat: add mask to token create and update

---

src/types/models/tokens.ts
test/tokenize.test.ts
test/tokens.test.ts

- Adds `expires_at` prop to token and token create request

feat: add token expires_at

---

package.json
yarn.lock

chore: updates dependencies

---

src/types/models/banks.ts
src/types/models/cards.ts
src/types/models/index.ts

- Add card and bank types back

feat: add card and bank types

---

src/types/models/tokens.ts
test/tokenize.test.ts
test/tokens.test.ts

- Adds container property to Token types
- Updates unit tests

feat: adds container property to tokens

---

src/types/elements/events.ts

- Add card last 4 to card change event

feat: add card last 4 to card change event

---

src/types/elements/elements.ts

- Adds `focus` and `blur` methods to `BaseElement`

feat: add focus and blur methods to base element

---

src/types/elements/options.ts

- Fix value in sanitized options

fix: fix value in sanitized options

---

src/types/models/applications.ts

- Add `expiring` application type

feat: add expiring application type

---

src/BasisTheory.ts
src/common/constants.ts
src/common/utils.ts
src/elements/services/proxy.ts
src/proxy/BasisTheoryProxy.ts
src/proxy/index.ts
src/types/elements/elements.ts
src/types/elements/services/index.ts
src/types/elements/services/proxy.ts
src/types/sdk/sdk.ts
src/types/sdk/services/index.ts
src/types/sdk/services/proxy.ts
test/clients.test.ts
test/elements/proxy.test.ts
test/proxy.test.ts

- Adds `proxy` client, including elements delegate.

feat: add proxy client

---

src/types/elements/events.ts

- Adds `cardBin` to `CardChangeEvent`

feat: add cardBin to card change event

---

src/BasisTheory.ts
src/elements/services/index.ts
test/init.test.ts

- Adds proxy delegate method to main class (fix)

fix: add proxy delegate to btjs

---

src/BasisTheory.ts
src/common/constants.ts
src/sessions/BasisTheorySessions.ts
src/sessions/index.ts
src/types/models/applications.ts
src/types/sdk/sdk.ts
src/types/sdk/services/index.ts
src/types/sdk/services/sessions.ts
test/clients.test.ts
test/sessions.test.ts

-This is a PR to add support for creating a session, and authorizing a session in the JS SDK.

feat: support creating & authorizing sessions

---

src/types/models/applications.ts
test/applications.test.ts

- Removing support for expiring apps

feat: remove expiring applications support

---

src/types/elements/events.ts

- add valid and maskSatisfied flags

feat: add valid and maskSatisfied flags

---

src/sessions/BasisTheorySessions.ts
test/sessions.test.ts

fix: fix sessions endpoints

---

src/BasisTheory.ts
src/types/elements/elements.ts
src/types/elements/options.ts

- Make `apiKey` optional when loading elements

feat: make apiKey optional for loading elements

---

src/types/elements/options.ts

- feat: add support for validation onChange

feat: add support for validation onChange

---

src/types/elements/options.ts

- fix: remove validateOnChange from update types

fix: remove validateOnChange from update methods types

---

src/proxy/BasisTheoryProxy.ts

- fix: remove trailing slash from options path
https://linear.app/basis-theory/issue/ENG-4219/fixes-issue-with-invoking-proxy-in-btjs

fix: remove trailing slash from options path

---

src/types/elements/options.ts

feat: add enableCopy flag

---

src/types/elements/elements.ts

fix: make CardMetadata optional

---

src/types/elements/shared.ts

fix: make maskSatisfied optional

---

README.md
src/common/constants.ts
src/common/utils.ts
src/types/sdk/services/shared.ts
test/applications.test.ts
test/permissions.test.ts
test/reactors.test.ts
test/setup/utils.ts
test/tenants.test.ts
test/tokenize.test.ts
test/tokens.test.ts
test/utils.test.ts

- Adding idempotency key header

feat: adding idempotency key header

---

src/types/sdk/services/reactors.ts
test/reactors.test.ts

- Adding async reactors params

feat: add async reactor params

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

created cf cache purge

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
scripts/setupinfra.sh
scripts/writelibvars.sh

- edits for new dev domain
-
- minimal

edits for new dev domain

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

- Fixes issue where dev script would not get uploaded

fix: fix issue w dev script

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
scripts/setupinfra.sh

- tf work for new s3 config for js
-
- minimal

feat: tf work for new s3 config for js

---

.github/workflows/release.yml

- fix: pipeline fix for release
-
- minimal

fix: pipeline fix for release

---

scripts/setupinfra.sh

fix: remove prod for aws s3

---

scripts/setupinfra.sh

- fix: remove prod call for state pull

fix: remove prod call for state pull

---

scripts/setupinfra.sh

- chore: add condition for dev only push for s3

chore: add condition for dev only push for s3

---

scripts/setupinfra.sh

- chore:s3 static content for prod

chore:s3 static content for prod

---

.github/workflows/release.yml

- chore: purge url for prod
-
- minimal

chore: purge url for prod

---

cypress/integration/elements.spec.ts
scripts/writelibvars.sh

- Updates hosted elements hosts after App Service decom

fix: update hosted elements hosts

---

src/BasisTheory.ts
src/service/types.ts
src/types/sdk/sdk.ts
webpack.common.js
yarn.lock

- removes dependency from node `https` package, fixes webpack browser builds

fix: remove node https dependency

---

src/BasisTheory.ts
src/common/constants.ts
test/clients.test.ts

- reverts the default agent config that was causing issues w/ node apps

fix: revert default agent settings

---

src/proxy/BasisTheoryProxy.ts

- feat: limit exposure of headers to post reqs to proxy

feat: limit exposure of response headers to post reqs in proxy

---

src/types/elements/elements.ts

- Adds the `mount(element: Element)` overload to Elements types.

feat: add mount overload that allows html element argument

---

README.md
src/BasisTheory.ts
src/common/constants.ts
src/common/utils.ts
src/transactions/BasisTheoryTransactions.ts
src/transactions/index.ts
src/types/sdk/sdk.ts
src/types/sdk/services/index.ts
src/types/sdk/services/shared.ts
src/types/sdk/services/transactions.ts
test/clients.test.ts
test/setup/utils.ts
test/tokenize.test.ts
test/tokens.test.ts
test/transactions.test.ts
test/utils.test.ts

feat: supporting transactions

---

package.json
src/common/utils.ts
src/proxies/BasisTheoryProxies.ts
src/reactors/BasisTheoryReactors.ts
src/service/BasisTheoryService.ts
src/sessions/BasisTheorySessions.ts
src/tokens/BasisTheoryTokens.ts
src/transactions/BasisTheoryTransactions.ts
test/proxy.test.ts
test/setup/utils.ts
yarn.lock

chore: update dependencies

---

.eslintrc.js
cypress/integration/credit-card.spec.ts
src/common/utils.ts
src/types/elements/options.ts
test/applications.test.ts
test/proxies.test.ts
test/reactors.test.ts
test/sessions.test.ts
test/setup/utils.ts
test/tenants.test.ts
test/tokens.test.ts
test/transactions.test.ts

- Adds proper casing support if response is list for Tokens, Reactors, Proxies

fix: fix casing for list tokens, reactors, proxies responses

---

cypress/fixtures/crud_client.html
cypress/integration/proxies.spec.ts
cypress/integration/reactors.spec.ts
cypress/support/commands.ts
cypress/support/index.d.ts
src/proxies/BasisTheoryProxies.ts
src/reactors/BasisTheoryReactors.ts
src/service/CrudBuilder.ts
src/types/models/proxies.ts
src/types/models/reactors.ts
src/types/sdk/services/proxies.ts
src/types/sdk/services/reactors.ts
src/types/sdk/services/sessions.ts
src/types/sdk/services/shared.ts
test/proxies.test.ts
test/reactors.test.ts
test/setup/utils.ts

feat: add proxies and reactors patch method

---

src/types/elements/elements.ts

- feat: adds format function to card expiration date

feat: adds format function to card expiration date

---

src/types/models/index.ts
src/types/models/proxies.ts
src/types/models/reactors.ts
src/types/models/util.ts
test/proxies.test.ts

fix: remove deprecated proxy reactors and fix patch types

---

src/types/models/proxies.ts
src/types/models/reactors.ts

fix: replace patch configuration type

---

src/BasisTheory.ts
src/common/BasisTheoryClient.ts
src/types/elements/elements.ts
src/types/sdk/sdk.ts
src/types/sdk/services/http.ts
src/types/sdk/services/index.ts

Fixes BT HTTP client method types

fix: http method types

---

scripts/writelibvars.sh
src/common/utils.ts

fix: fixes user-agent detection in React Native

---

src/service/BasisTheoryService.ts

- Throw error prompting users to downgrade CRA 5, known issue reported [here](https://github.com/facebook/create-react-app/issues/11889)

fix: throw error if axios doesnt resolve

---

src/service/BasisTheoryService.ts

- Sending error message to Basis Theory JS issue

chore: updating CRA error message

---

jest.config.js
package.json
src/types/elements/options.ts
yarn.lock

- feat: adds readOnly to elements
- feat: use swc for jest tests

feat: adds readOnly to elements

---

src/types/elements/options.ts

- feat: adds inputMode to elements options
- style: sort things alphabetically

feat: adds inputMode to elements options

---

README.md

chore: updating api keys examples

---

.github/workflows/pull-request.yml
package.json
yarn.lock

- Upgrade deps
- Add concurrency group so previous workflows are cancelled when same branch pushed.

chore: upgrade deps and add concurrency group

---

README.md
src/BasisTheory.ts
src/types/models/reactor-formulas.ts
src/types/models/reactors.ts
src/types/sdk/services/reactor-formulas.ts
test/reactors.test.ts

- feat: adds code and deprecates reactor formulas

feat: adds code and deprecates reactor formulas

---

README.md
src/BasisTheory.ts
src/types/elements/elements.ts
src/types/elements/options.ts
src/types/sdk/sdk.ts
test/elements.test.ts

- adds use NG api flag for elements

fix: adds use NG api flag for elements

---

.eslintrc.js
cypress/e2e/applicationTemplates.cy.ts
src/BasisTheory.ts
src/application-templates/BasisTheoryApplicationTemplates.ts
src/application-templates/index.ts
src/common/constants.ts
src/types/models/application-templates.ts
src/types/sdk/sdk.ts
src/types/sdk/services/application-templates.ts
src/types/sdk/services/index.ts
test/application-templates.test.ts
test/clients.test.ts
test/permissions.test.ts
test/setup/utils.ts

feat: add applicationTemplates client

---

package.json
yarn.lock

feat: patch axios

---

package.json
yarn.lock

 feat: patch axios

---

src/types/sdk/services/shared.ts
test/logs.test.ts
test/setup/utils.ts

- Support logs cursor pagination

feat: support logs cursor pagination

---

src/types/elements/elements.ts

- feat: adds setValueRef to elements

feat: adds setValueRef to elements

---

src/types/elements/elements.ts

- fix: remove value setter generic for setValueRef

fix: remove value setter generic for setValueRef

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
scripts/setupinfra.sh

- adds deploy only to new s3 origins

chore: new s3 storage backend

---

src/BasisTheory.ts
src/common/constants.ts
src/threeds/BasisTheoryThreeDs.ts
src/threeds/index.ts
src/types/models/threeds.ts
src/types/sdk/sdk.ts
src/types/sdk/services/index.ts
src/types/sdk/services/threeds.ts
test/clients.test.ts
test/threeds.test.ts

feat: add 3ds client

---

.github/workflows/pull-request.yml
.github/workflows/release.yml

- remove ng aws deploy
- moving to cloudflare r2
- cleanup work

chore: remove ng aws deploy

---

src/types/models/tenants.ts
test/tenants.test.ts

-  updating token usage report

feat: updating token usage report

---

src/types/elements/options.ts
src/types/elements/styles.ts

feat: adds copyIconStyles

---

src/types/elements/options.ts

fix: add missing types

---

src/types/elements/styles.ts

- fix: typo in copy icon styles prop

fix: typo in copy icon styles prop

---

src/types/elements/options.ts

- feat: adds maxLength to text element

feat: adds maxLength to text element

---

cypress/e2e/credit-card.cy.ts

Change redirect location in Cypress test case
-

fix: change redirect to static URL for cypress test

---

package.json
yarn.lock

fix: patch axios

---

src/threeds/BasisTheoryThreeDs.ts
test/threeds.test.ts

- fix: corrects 3ds request paths

fix: corrects 3ds request paths

---

.github/workflows/pull-request.yml
scripts/setupinfra.sh

- ENG-7268: publish hashes of script to be used to verify integrity on client side

feat: add script integrity checks for BT-JS

---

src/BasisTheory.ts
src/common/constants.ts
src/elements/services/index.ts
src/elements/services/token-intents.ts
src/token-intents/BasisTheoryTokenIntents.ts
src/token-intents/index.ts
src/types/elements/elements.ts
src/types/elements/services/index.ts
src/types/elements/services/token-intents.ts
src/types/models/index.ts
src/types/models/token-intents.ts
src/types/sdk/sdk.ts
src/types/sdk/services/index.ts
src/types/sdk/services/token-intents.ts
test/clients.test.ts
test/init.test.ts
test/token-intents.test.ts

feat: adds token-intents

---

.github/workflows/release.yml

chore: remove deprecated workflow step

---

src/common/utils.ts
src/token-intents/BasisTheoryTokenIntents.ts
src/types/models/shared.ts
src/types/models/token-intents.ts
src/types/models/tokens.ts
test/token-intents.test.ts

- adds token transformers to token-intents service

fix: adds token transformers to token-intents service

---

.github/workflows/release.yml

- release doesn't require approval

ci: does not require approval

---

src/types/elements/shared.ts

- feat: add errors to element metadata

feat: add errors to element metadata

---

scripts/setupinfra.sh

- Set content-type text/plain for script hash

chore: set content-type on JS hash file to avoid browser download

---

src/types/elements/options.ts

- feat: adds support for custom card element placeholder

feat: add support for custom card element placeholder

---

src/types/models/card-details.ts
src/types/models/tokens.ts
test/tokens.test.ts

- Add the `cardDetails` object to enrichments

feat: add card details to enrichments

---

.github/workflows/release.yml

ci: update release notification vars

---

src/types/models/token-intents.ts

- feat: add authentication to TokenIntentCardDetails

feat: add authentication to TokenIntentCardDetails

---

src/BasisTheory.ts
src/types/elements/elements.ts
src/types/elements/options.ts
src/types/sdk/sdk.ts
test/elements.test.ts

- feat: adds `disableTelemetry` init option

 feat: adds `disableTelemetry` init option

---

.github/workflows/pull-request.yml
.github/workflows/release.yml
package.json
scripts/writelibvars.sh
src/BasisTheory.ts
src/common/constants.ts
src/common/telemetry-logging.ts
src/elements/constants.ts
src/elements/load.ts
src/types/elements/elements.ts
src/types/sdk/sdk.ts
test/elements.test.ts
yarn.lock

- Adds datadog telemetry
- Move disableTelemetry option to also being able to disable it for the sdk
- Adds logs around elements script loading

feat: add telemetry for elements script

---

src/common/telemetry-logging.ts
src/types/elements/elements.ts

- Avoid re-initializing dd logger

fix: avoid re-initializing logger

---

README.md

- updating deprecation notice to clarify continued support for web elements and reactor enviroinments

chore: updating deprecation notice

---

cypress/e2e/elements.cy.ts
src/common/utils.ts
src/elements/constants.ts
src/elements/load.ts

- Retry 1x to load the elements script on error event

feat: add retry for elements script

---

src/common/logging.ts

fix: safe escape logging ops

---

src/types/elements/options.ts

- Add missing `debug` option in elements internal options type

fix: add missing debug elements option

---

src/BasisTheory.ts
src/types/elements/elements.ts
test/elements.test.ts

feat: add debug to element internal options

---

src/elements/load.ts

- Add proper fetch response to logs plus more details
- Return on promises so it doesn't fall through on rejections
- Remove unnecessary assertions

fix: improve logging for elements script loading

---

cypress/e2e/elements.cy.ts
src/elements/load.ts

- feat: pin btjs to web-elements 1.5.0

feat: pin btjs to web-elements 1.5.0

---

src/elements/load.ts

fix: bump elements version

---

src/types/models/tenants.ts
test/tenants.test.ts

- Adding new attibute `totalTokens` at root level of Usage Report endpoint

feat: adding totalTokens in usage endpoint at root level

---

scripts/writelibvars.sh

- fix: remove hardcoded elements path

fix: remove hardcoded elements path

---

scripts/writelibvars.sh
src/common/constants.ts
src/elements/load.ts

fix: revert to elements 1.5

---

.github/workflows/pull-request.yml
.rclone.conf
makefile
scripts/deploy-to-r2.sh

feat: parallel r2 deploy

---

.github/workflows/release.yml
.rclone.uat.conf
scripts/deploy-to-r2.sh

feat: add uat deployment
