Basis-Theory/basis-theory-js

- infrastructure/index.ts
- library/babel.bundle.config.js
- library/package.json
- library/prepare.js
- library/src/index.ts
- library/webpack.common.js
- yarn.lock
Removes bundled JS file from publishable package. `main` attribute now points to Babel-transpiled `index.js`.
A new variable `_instance` is exported for the sake of [exposing the library](https://webpack.js.org/guides/author-libraries/#expose-the-library) but it is not meant to be used in Node environments.
Old `default` export meant for bundle has been removed to prevent unwanted behavior, such as multiple `init` calls in same instance, or importing instance methods/props directly. This is not considered a breaking change, for this has never been documented/recommended, and was an internal solution.
> ENG-1275 - fix: remove bundled file from package

- library/src/applications/types.ts
- library/src/atomic/types.ts
- library/src/reactor-formulas/types.ts
- library/src/reactors/types.ts
- library/src/tenants/types.ts
- library/src/tokens/types.ts
- library/src/types.ts
- library/test/applications.test.ts
- library/test/atomic-banks.test.ts
- library/test/atomic-cards.test.ts
- library/test/tenants.test.ts
- library/test/tokens.test.ts
- Adds standard audit fields on all auditable entities
- _Note: We will treat this as a feature, but this may be a breaking change for consumers that expected audit fields to be non-null. We will make a pass through the UI's to ensure nulls are handled appropriately._
> feat: Standardizing audit fields across entities

- library/src/service/BasisTheoryService.ts
- library/test/clients.test.ts
- yarn.lock
- `User-Agent` header will not be set if client is a browser. 
This behavior is blocked by the browser and throws console errors.
> ENG-2321 - fix: only add User-Agent header if client is not a browser

- src/types/models/tokens.ts
- test/tokenize.test.ts
- test/tokens.test.ts
- Add id to create token request
> feat: add id to create token request

- src/types/elements/options.ts
- Adds `value` prop to creation object for all Elements.
> feat: add value prop to elements create and update objects

- src/elements/services/tokens.ts
- src/types/elements/options.ts
- src/types/elements/services/tokens.ts
- src/types/elements/shared.ts
- Adds token `retrieve` method and data reference types for elements.
> feat: add retrieve method, data reference types for reveal elements

- src/types/models/applications.ts
- src/types/models/tokens.ts
- test/applications.test.ts
- test/tokens.test.ts
- Adds support for access rules on applications
- Adds support for containers on tokens
> feat: adds support for access rules and containers

- src/types/elements/options.ts
- Add separation where `create` and `update` element values are static and `setValue` values are `reference`
> feat: add separation between card elements static and reference values

- src/BasisTheory.ts
- src/elements/services/tokens.ts
- src/tokens/BasisTheoryTokens.ts
- src/types/elements/elements.ts
- src/types/elements/options.ts
- src/types/elements/services/tokens.ts
- src/types/sdk/services/tokens.ts
- Adds `setValue`methods to all elements
- Set type for token `data` as `any` on retrieve
- without this you couldn't do `token.data.<someprop>` w/o casting to `any`
- Set `apiKey` type as `string | undefined` to avoid having to cast environment variables
- Change value of expiration/month year to `number` where applicable to match API
- Allow `string` to be passed as a `static` value to `CardExpirationDateElement`
> feat: add setValue method to elements, other qol improvements

- src/types/models/applications.ts
- src/types/models/tokens.ts
- test/applications.test.ts
- test/tokens.test.ts
- Add `expiresAt` and `canCreateExpiringApplications` to `Application`
> feat: add support for expiring applications

- src/types/models/applications.ts
- Adds `expiresAt` and `canCreateExpiringApplications` to `CreateApplication` model
- Adds `canCreateExpiringApplications` to `UpdateApplication` model
> fix: add expiring application props to create and update models

- src/common/utils.ts
- src/proxies/BasisTheoryProxies.ts
- src/types/models/proxies.ts
- src/types/models/reactors.ts
- test/proxies.test.ts
> feat: add new proxy attributes

- babel.bundle.config.js
- babel.config.js
- package.json
- src/common/BasisTheoryApiError.ts
- src/common/BasisTheoryValidationError.ts
- yarn.lock
- Adds `babel-plugin-transform-builtin-extend` plugin to fix issue where custom Error class constructors were unrecognized when using `instanceof`.
References:
[MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error#custom_error_types)
[Plugin Repo](https://github.com/loganfsmyth/babel-plugin-transform-builtin-extend)
> fix: fix transpiling issue for custom error classes

- src/BasisTheory.ts
- src/elements/load.ts
- src/types/sdk/sdk.ts
- test/elements.test.ts
- Allows setting an `elementsClientUrl` to specify where from to load the client (for debugging purposes).
> feat: allow changing the elements client url

- src/BasisTheory.ts
- src/common/BasisTheoryClient.ts
- src/common/HttpClientError.ts
- src/common/index.ts
- src/types/elements/elements.ts
- test/elements/httpClient.test.ts
- adds interface for client for dual writing
- doesn't look like we have any tests for actually testing the calls from BT.js over to elements. it's probably fine, but currently questioning how we could test this integration
- waiting on Elements to be deployed to prod
> feat: adds interface for client for dual writing

- src/permissions/BasisTheoryPermissions.ts
- src/types/sdk/services/permissions.ts
- test/permissions.test.ts
⚠️  Possible breaking change: adding query parameter to `permissions.list` method will break users passing custom request options.
> feat: support application type query param in permissions list

- src/types/elements/elements.ts
> fix: revert setValue types

- src/BasisTheory.ts
- src/applicationKeys/BasisTheoryApplicationKeys.ts
- src/applicationKeys/index.ts
- src/applications/BasisTheoryApplications.ts
- src/common/constants.ts
- src/types/models/applications.ts
- src/types/sdk/sdk.ts
- src/types/sdk/services/applicationKeys.ts
- src/types/sdk/services/index.ts
- test/applicationKeys.test.ts
- test/applications.test.ts
- test/clients.test.ts
> feat: add application keys endpoints

- src/types/models/threeds.ts
- test/threeds.test.ts
- Adds `token_id` and `token_intent_id` to 3ds session creation, deprecates pan
- Add decoupled challenge props for 3ds authentication.
> feat: support token intents in 3ds, add mit props

- src/types/elements/events.ts
- src/types/elements/shared.ts
refactor: reuse existing element metadata and card metadata interfaces
- feat: adds metadata to blur event
> feat: adds metadata to blur event

- src/BasisTheory.ts
- src/types/elements/options.ts
- test/clients.test.ts
- test/elements.test.ts
- Allow API base urls with subpaths
- Context: we were removing trailing slash but when doing `new URL` that strips the path if its not included
- Fix was to manually add back a trailing slash at the end of the url after we strip any existing ones (could be multiple)
- Add `useSameOriginApi` prop in a missed place
> fix: allow api base urls with subpaths

- src/BasisTheory.ts
- src/common/BasisTheoryApiError.ts
- src/common/constants.ts
- src/common/utils.ts
- src/service/BasisTheoryService.ts
- src/service/types.ts
- src/types/models/token-intents.ts
- src/types/models/tokenize.ts
- src/types/models/tokens.ts
- src/types/sdk/sdk.ts
- src/types/sdk/services/sessions.ts
- Add `debug` init option that will add a `_debug` object containing `bt-trace-id` and `cf-ray` response headers
> feat: add debug init option
